schema_version = "1.0.0"
id = "wheel_pkg_test"
name = "Test Wheel Package"
version = "0.0.1"
tagline = "Example extentions that uses a wheel package"
maintainer = "Community"
type = "add-on"
tags = ["Object"]
blender_version_min = "4.2.0"
license = ["SPDX:MIT", "SPDX:GPL-2.0-or-later"]
copyright = ["2024 Community"]
platforms = ["windows-x64", "linux-x64", "macos-arm64", "macos-x64"]
wheels = [
    "./wheels/humanize-4.10.0-py3-none-any.whl",
    "./wheels/pillow-10.4.0-cp311-cp311-macosx_10_10_x86_64.whl",
    "./wheels/pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pillow-10.4.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/pillow-10.4.0-cp311-cp311-win_amd64.whl",
]
